### ISSUE TITLE
Support Hue Labs

### ISSUE THREAD

**Issue by DorianStrasser** [hass-emulated-hue/core#108]
**Is your feature request related to a problem? Please describe.**
I want to replace hue bridge completely, but am a heavy user of lab scenes. Right now I neither can install nor use Lab scenes

**Describe the feature that you would like to be added**
On the original hue app I would like to be able to install and use scenes directly from the labs section. 

**Describe alternatives you've considered**
Stay with the Hue bridge for now.

**Describe your use case for this feature**
I want to replace hue bridge completely.

**Additional context**
Right now I get the following warning message when trying to install a lab scene:

```
2021-02-10 14:11:51,145 WARNING emulated_hue.api -- Invalid/unknown request: <Request POST /api/35335d9e-663b-449f-8d3a-15b009567124/sensors/ > --> {'name': '$colorSet', 'modelid': 'HUELABSVDIMMER', 'swversion': '1.0', 'type': 'CLIPGenericStatus', 'manufacturername': 'Philips', 'uniqueid': 'bb59-eb5a-4c6b-9042', 'recycle': True}
```

**Comment by alexyao2015** [comment]
Unfortunately, Hue Labs is a cloud connected service and we have no way to connect to it as it's a proprietary service. This will never be possible to implement as a feature. In the case of scenes, consider taking a look at hass scenes as an alternative.

**Comment by alexyao2015** [comment]
Just to be sure I cover all bases, if it's not related to the cloud connected service (home/away, etc) it would be a duplicate of #50 which we plan to implement.

**Comment by DorianStrasser** [comment]
Thank you for the quick reply and sorry for my duplicate post!
