### ISSUE TITLE
Binary sensor emulated_hue_entertainment_active not updating

### ISSUE THREAD

**Issue by henriklund** [hass-emulated-hue/core#115]
**Describe the bug**
I am trying to access the binary sensor emulated_hue_entertainment_active, however, I am unable to locate this in either Developer Tools (under states), in Configuration (as an entity) or in Node-RED.

**Steps to Reproduce**
1. Go to Developer Tools
2. Select tab States
3. Type in the sensor -> nothing found

**Expected behavior**
Binary sensor would show up.

**Logs**
N/A

**Hardware Info:**
 - Architecture (Ex: x86, ARM): x86
 - Addon version (Ex: stable or dev): Stable v.0.2.1
    - Value of "tag_commit_or_branch" if using dev: 
 - OS (Ex: Windows 10, Ubuntu Buster): Hassio v.2021.2.3
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Intel NUC

**Additional context**
N/A

**Comment by henriklund** [comment]
After submitting the bug report, the binary sensor now emerged(!). However, the sensor does not appear to change state; it is in state 'off' despite Ambilight+Hue is activated on a paired TV. The connected Hue lights react as expected (changes state - a lot), however, the the sensor emulated_hue_entertainment_active remains off.
Looking at the entity, I see:
![image](https://user-images.githubusercontent.com/8402745/107923975-88fa6c00-6f72-11eb-8815-3c0a09905800.png)
(This covers a 'No logbook entries found'

**Comment by alexyao2015** [comment]
The sensor only turns on when entertainment is active. Some services for not use entertainment mode but rather use the default hue protocol for communication. This includes apps like iLightShow. For these apps, the sensor will not be active. If you try the test entertainment mode in the hue app and it still does not turn on, that would be a big.
