### ISSUE TITLE
0.2.4 version hangs when configuring light

### ISSUE THREAD

**Issue by zewelor** [hass-emulated-hue/core#127]
**Describe the bug**

When doing clean configuration, on newest version of emulated-hue, I got following error, and TV hangs.

**Steps to Reproduce**

**Expected behavior**

**Logs**
```
emulated-hue                      | 2021-02-27 07:57:26,216 DEBUG emulated_hue.api -- Start Entertainment mode for group 7 - params: {'stream': {'active': True}}
emulated-hue                      | 2021-02-27 07:57:26,222 DEBUG emulated_hue.discovery -- Serving SSDP discovery info to ('192.168.1.12', 49155)
emulated-hue                      | 2021-02-27 07:57:26,225 INFO  emulated_hue.entertainment -- Start HUE Entertainment Service on UDP port 2100.
emulated-hue                      | Not a hex number 'P9MDGFLLIKLKGXB1CNA39AFJQVSMO8FS'
```

**Hardware Info:**
 - Architecture (Ex: x86, ARM): 
 - Addon version (Ex: stable or dev): 
    - Value of "tag_commit_or_branch" if using dev: 
 - OS (Ex: Windows 10, Ubuntu Buster): 
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): 

**Additional context**

**Comment by alexyao2015** [comment]
Thanks for reporting this! You'll need to remove the username from the config manually to and reauthenticate to generate a new clientkey since previously generated ones were faulty. Will push out 0.2.5 shortly to fix this.

**Comment by zewelor** [comment]
Ok, thanks for quick fix !
