### ISSUE TITLE
Unable to install dev addon on RPI4

### ISSUE THREAD

**Issue by nunodsrodrigues** [hass-emulated-hue/core#138]
**Describe the bug**

Unable to install the dev addon on a RPI4.

**Steps to Reproduce**

1. Go to Supervisor -> Add-on Store -> Emulated HUE (dev)
2. Click Install

**Expected behavior**

Nothing happens and the addon isn't installed.

**Logs**

/var/log/syslog:
```
hassio-supervisor[1801]: #033[31m21-03-11 23:05:22 ERROR (SyncWorker_5) [supervisor.docker.addon] Can't build 7c966942/armv7-addon-emulated_hue_dev:dev-0.0.1: The command '/bin/sh -c wget -O /tmp/base.tar.gz "https://github.com/hass-emulated-hue/s6-overlay-base/archive/master.tar.gz"     && mkdir -p /tmp/base     && tar zxvf /tmp/base.tar.gz --strip 1 -C /tmp/base     && mv /tmp/base/* .' returned a non-zero code: 1#033[0m
hassio-supervisor[1801]: #033[31m21-03-11 23:05:22 ERROR (SyncWorker_5) [supervisor.docker.addon] Build log:
hassio-supervisor[1801]: Step 1/12 : FROM alpine:latest as downloader
hassio-supervisor[1801]:  ---> 9c74a18b2325
hassio-supervisor[1801]: Step 2/12 : WORKDIR /base
hassio-supervisor[1801]:  ---> Using cache
hassio-supervisor[1801]:  ---> 8923c21e14a8
hassio-supervisor[1801]: Step 3/12 : RUN wget -O /tmp/base.tar.gz "https://github.com/hass-emulated-hue/s6-overlay-base/archive/master.tar.gz"     && mkdir -p /tmp/base     && tar zxvf /tmp/base.tar.gz --strip 1 -C /tmp/base     && mv /tmp/base/* .
hassio-supervisor[1801]:  ---> Running in c9e6c7aea38a
hassio-supervisor[1801]: #033[91mwget: bad address 'github.com'
hassio-supervisor[1801]: #033[0m
hassio-supervisor[1801]: Removing intermediate container c9e6c7aea38a
hassio-supervisor[1801]: #033[0m
```

**Hardware Info:**
 - Architecture (Ex: x86, ARM): ARM
 - Addon version (Ex: stable or dev): dev
    - Value of "tag_commit_or_branch" if using dev: dev-0.0.1
 - OS (Ex: Windows 10, Ubuntu Buster): Raspbian (Buster)
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Raspberry Pi 4

**Additional context**

**Comment by alexyao2015** [comment]
That looks like dns isn't working in your host. This isn't a bug with the addon.

**Comment by nunodsrodrigues** [comment]
I don't find any problem with the DNS, this is the only addon that I'm unable to install. The non-dev installs with no problem.

**Comment by alexyao2015** [comment]
Try running this through ssh or the terminal:
```
docker run -it --rm alpine /bin/sh
```
You should now see a shell prompt and be dropped within the container terminal

Try running these two commands and post the output:
```
wget -O /tmp/base.tar.gz "https://github.com/hass-emulated-hue/s6-overlay-base/archive/master.tar.gz"
nslookup github.com
```

**Comment by nunodsrodrigues** [comment]
```
/ # wget -O /tmp/base.tar.gz "https://github.com/hass-emulated-hue/s6-overlay-base/archive/master.tar.gz"
wget: bad address 'github.com'
/ # nslookup github.com
nslookup: clock_gettime(MONOTONIC) failed
```

**Comment by nunodsrodrigues** [comment]
Fixed by installing libseccomp2_2.4.4-1~bpo10+1_armhf.deb. It seems that raspbian needs a version greater than 2.4.2 (not provided via repo) with the latest alpine version.

Thanks for your help!

**Comment by alexyao2015** [comment]
You installed that on the host and it worked? Thats interesting given that the container should be isolated. Where did you find that information to install that? 

Anyways, glad you figured it out!

**Comment by nunodsrodrigues** [comment]
Yes, on the host and now the addon up and running.

I found the solution here: https://github.com/dperson/openvpn-client/issues/365#issuecomment-787133320

Regards.

**Comment by alexyao2015** [comment]
Great, it seems like v3.13 of alpine is having issues, so I've version pinned it to 3.12 for now so it hopefully doesn't affect anyone else.
