### ISSUE TITLE
500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by stanwebber** [hass-emulated-hue/core#146]
**Describe the bug**

unable to pair bridge in any app (official or third-party)

**Steps to Reproduce**

pairing process proceeds normally until the link enable button is pressed and pairing fails

**Expected behavior**

bridge pairs with app

**Logs**

no errors registered on hass server. 500 error output on client app

**Hardware Info:**
 - Architecture (Ex: x86, ARM): rpi4 x64 (server), android8 arm (client)
 - Addon version (Ex: stable or dev): 0.2.6 stable and 0.0.1dev (4-30-21 build)
    - Value of "tag_commit_or_branch" if using dev: 
 - OS (Ex: Windows 10, Ubuntu Buster): hassos
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): rpi4 2gb

**Additional context**

I used to have this addon working beautifully with ALL hue apps back on v0.0.x, but since then it's been hopelessly broken and I've ignored doing anything about it. now I'm getting serious again, but I can't even get started. i've uninstalled/reinstalled/rebuilt both the stable and dev plugins, restarting hass between each step, but i keep getting this same error regardless when attempting to pair the bridge:

Unexpected response from bridge.
500 Internal Server Error.
Text: '500 Internal Server Error Server got itself in trouble'

the hue apps auto detect the bridge on the network and I get the link enable notification in hass. I notice that hass itself auto detects the emulated hue bridge under integrations, which I never remembered seeing before. I also have a physical v1 hue bridge on the network, but I've input manual IP addresses to rule out confusion when pairing.

this type of error strikes me as very rudimentary. what simple thing am I overlooking?

**Comment by alexyao2015** [comment]
If you could fill out all the information requested in the template, I could provide some help. Otherwise, there is no way I can provide any help.

**Comment by alexyao2015** [comment]
Proper logs would be helpful

**Comment by stanwebber** [comment]
forget it. not worth dealing with you over it
