### ISSUE TITLE
KeyError: 'lightstates'

### ISSUE THREAD

**Issue by cdhmri5** [hass-emulated-hue/core#147]
**Describe the bug**

Hue app will not pair.

**Steps to Reproduce**

1. Hue app detects emulated bridge.
2. Link notification appears in Home Assistant.
3. Link button is pressed.
4. Hue app times out trying to pair.

**Expected behavior**

Hue app pairs with emulated bridge.

**Logs**

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-set-vars.sh: executing... 
[cont-init.d] 00-set-vars.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:49:21] INFO: Starting Emulated Hue...
2021-04-30 14:49:23,644 INFO  emulated_hue.config -- Auto detected listen IP address is 10.10.10.106
2021-04-30 14:49:23,701 DEBUG getmac -- Raw MAC found: None
2021-04-30 14:49:23,706 DEBUG getmac -- Raw MAC found: dc:a6:32:13:ff:9b
2021-04-30 14:49:23,708 DEBUG aiorun -- Entering run()
2021-04-30 14:49:23,733 DEBUG aiorun -- Creating default executor
2021-04-30 14:49:23,786 INFO  hass_client -- Connected to Home Assistant ws (version 2021.4.6)
2021-04-30 14:49:24,003 INFO  emulated_hue.api -- Started HTTP webserver on port 80
2021-04-30 14:49:24,182 INFO  emulated_hue.api -- Started HTTPS webserver on port 443
2021-04-30 14:49:24,184 DEBUG emulated_hue.discovery -- Starting mDNS/uPNP discovery broadcast...
2021-04-30 14:49:32,030 DEBUG emulated_hue.discovery -- Serving SSDP discovery info to ('10.10.10.106', 56134)
2021-04-30 14:49:36,532 DEBUG emulated_hue.api -- [10.10.10.113] GET /api/nouser/config
2021-04-30 14:49:36,533 INFO  emulated_hue.config -- Link request detected - Use the Homeassistant frontend to confirm this link request.
2021-04-30 14:49:40,954 DEBUG emulated_hue.api -- [10.10.10.113] GET /api/nouser/config
2021-04-30 14:49:41,490 DEBUG emulated_hue.api -- [10.10.10.113] GET /api/nouser/config
2021-04-30 14:49:41,572 DEBUG emulated_hue.api -- [10.10.10.113] GET /api/f3e902a4-db55-41e8-badd-deabe94eea80
2021-04-30 14:49:41,672 ERROR aiohttp.server -- Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/app/emulated_hue/api.py", line 90, in wrapped_func
    return await func(cls, request)
  File "/app/emulated_hue/api.py", line 492, in get_full_state
    "scenes": await self.async_scene_to_full_state(),
  File "/app/emulated_hue/api.py", line 478, in async_scene_to_full_state
    del scene_data["lightstates"]
KeyError: 'lightstates'
2021-04-30 14:49:41,803 DEBUG emulated_hue.api -- [10.10.10.113] GET /api/nouser/config
2021-04-30 14:49:41,924 DEBUG emulated_hue.api -- [10.10.10.113] GET /api/nouser/config
2021-04-30 14:49:42,039 DEBUG emulated_hue.api -- [10.10.10.113] GET /api/f3e902a4-db55-41e8-badd-deabe94eea80
2021-04-30 14:49:42,070 ERROR aiohttp.server -- Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/app/emulated_hue/api.py", line 90, in wrapped_func
    return await func(cls, request)
  File "/app/emulated_hue/api.py", line 492, in get_full_state
    "scenes": await self.async_scene_to_full_state(),
  File "/app/emulated_hue/api.py", line 478, in async_scene_to_full_state
    del scene_data["lightstates"]
KeyError: 'lightstates'
2021-04-30 14:49:57,474 DEBUG emulated_hue.api -- [10.10.10.204] GET /link/efeAEDB490C8d3ea15148A68c21bbf99
2021-04-30 14:49:57,474 INFO  emulated_hue.config -- Link mode is enabled for the next 5 minutes.

**Hardware Info:**
 - Architecture (Ex: x86, ARM): 64-bit ARMv8
 - Addon version (Ex: stable or dev): 0.2.6 stable
    - Value of "tag_commit_or_branch" if using dev: 
 - OS (Ex: Windows 10, Ubuntu Buster): HASSOS 5.13
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): RPI 4

**Additional context**

**Comment by alexyao2015** [comment]
Can you provide your config file and provide the steps to reproduce this error from a completely clean config?

**Comment by cdhmri5** [comment]
What exactly do you mean by a completely clean config?

configuration.yaml:
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

light:
  - platform: switch
    name: ceiling fan
    entity_id: switch.ceiling_fan
  - platform: switch
    name: shop light
    entity_id: switch.shop_light
  - platform: switch
    name: stars
    entity_id: switch.stars
  - platform: group
    name: dining_room
    entities:
      - light.left_dining
      - light.right_dining
      - light.left_ambient
      - light.right_ambient
      - light.rear_ambient
  - platform: group
    name: nightstand
    entities:
      - light.left_nightstand
      - light.right_nightstand
  - platform: group
    name: backlight
    entities:
      - light.bias
      - light.etagere

logger:
    default: error

**Comment by alexyao2015** [comment]
Sorry can you provide your config.json file from the hass-emulated-hue folder, not your home assistant config? By clean config, delete the config.json file there and run it again. It should work without issues. Then try to reproduce this exact problem by redoing the steps that caused this error to occur in the first place.

**Comment by cdhmri5** [comment]
yes, removing the old config file solved the issue. it was not evident to me that uninstalling the add-on did not also reset the config as well. perhaps an option to factory reset under the configuration tab would let more users solve this problem for themselves. thanks

**Comment by alexyao2015** [comment]
If you would like to help improve the project please post the reproduction steps in the future.

**Comment by cdhmri5** [comment]
i think i know what's going on now. apparently, creating an entertainment group is causing the lightstates keyerror. here is the sequence of events that i've been able to re-create thru multiple trials and errors:

1. stop addon, delete emulated_hue.json, start addon
2. pair hue official and third-party apps
3. stop addon, backup emulated_hue.json, start addon
4. create 1 or more entertainment groups
5. all functions continue to work normally so long as the addon is running
6. stop addon, start addon
7. all hue apps are no longer able to connect, KeyError: 'lightstates' is output in log
8. stop addon, restore emulated_hue.json backup, start addon
9. all hue apps are able to reconnect
10. create 1 or more entertainment groups
11. all functions continue to work normally so long as the addon is running
12. stop addon, start addon
13. all hue apps are no longer able to connect, KeyError: 'lightstates' is output in log

2021-05-08 14:42:41,672 ERROR aiohttp.server -- Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/app/emulated_hue/api.py", line 90, in wrapped_func
return await func(cls, request)
File "/app/emulated_hue/api.py", line 492, in get_full_state
"scenes": await self.async_scene_to_full_state(),
File "/app/emulated_hue/api.py", line 478, in async_scene_to_full_state
del scene_data["lightstates"]
KeyError: 'lightstates'

**Comment by alexyao2015** [comment]
Can you post the two configs, the broken one and the working one from backup?

**Comment by cdhmri5** [comment]
emulated_hue.json with entertainment areas:
{
    "groups": {
        "1": {
            "action": {
                "on": false
            },
            "area_id": "1706bb0c3f2b42378d400e93ed5a67f3",
            "class": "Other",
            "enabled": true,
            "lights": [],
            "name": "",
            "sensors": [],
            "state": {
                "all_on": false,
                "any_on": true
            },
            "type": "Room"
        },
        "10": {
            "action": {
                "on": false
            },
            "area_id": "f638fd4c0b5d4ab7975f63478def6b74",
            "class": "Other",
            "enabled": true,
            "lights": [],
            "name": "",
            "sensors": [],
            "state": {
                "all_on": true,
                "any_on": true
            },
            "type": "Room"
        },
        "11": {
            "action": {
                "on": false
            },
            "area_id": "f080d8cd5787410b8672f30cc36281b9",
            "class": "Other",
            "enabled": true,
            "lights": [],
            "name": "",
            "sensors": [],
            "state": {
                "all_on": true,
                "any_on": true
            },
            "type": "Room"
        },
        "12": {
            "action": {
                "on": false
            },
            "area_id": "84b35f41fdd648d09b6d64d89b496f5e",
            "class": "Other",
            "enabled": true,
            "lights": [],
            "name": "",
            "sensors": [],
            "state": {
                "all_on": false,
                "any_on": true
            },
            "type": "Room"
        },
        "13": {
            "action": {
                "on": false
            },
            "area_id": "pat_s_house",
            "class": "Other",
            "enabled": true,
            "lights": [],
            "name": "",
            "sensors": [],
            "state": {
                "all_on": true,
                "any_on": false
            },
            "type": "Room"
        },
        "14": {
            "class": "TV",
            "lights": [
                "1",
                "12",
                "3",
                "19",
                "20",
                "21"
            ],
            "locations": {
                "1": [
                    1,
                    -1,
                    0
                ],
                "12": [
                    -1,
                    1,
                    1
                ],
                "19": [
                    -0.738174,
                    -1,
                    0
                ],
                "20": [
                    -1,
                    -0.738624,
                    0
                ],
                "21": [
                    -1,
                    -1,
                    0
                ],
                "3": [
                    1,
                    1,
                    0
                ]
            },
            "name": "living area",
            "stream": {
                "owner": "3cF4fDa0a29bc6C0B7848cB06D621Cf6AAA63A18",
                "proxymode": "auto",
                "proxynode": "/bridge"
            },
            "type": "Entertainment"
        },
        "15": {
            "class": "TV",
            "lights": [
                "13",
                "14",
                "15",
                "16",
                "9"
            ],
            "locations": {
                "13": [
                    -1,
                    1,
                    1
                ],
                "14": [
                    1,
                    -1,
                    1
                ],
                "15": [
                    1,
                    1,
                    1
                ],
                "16": [
                    -1,
                    -1,
                    1
                ],
                "9": [
                    0.004233,
                    -1,
                    0
                ]
            },
            "name": "family area",
            "stream": {
                "owner": "3cF4fDa0a29bc6C0B7848cB06D621Cf6AAA63A18",
                "proxymode": "auto",
                "proxynode": "/bridge"
            },
            "type": "Entertainment"
        },
        "16": {
            "class": "TV",
            "lights": [
                "4",
                "5"
            ],
            "locations": {
                "4": [
                    -1,
                    -1,
                    1
                ],
                "5": [
                    1,
                    1,
                    1
                ]
            },
            "name": "bedroom area",
            "stream": {
                "owner": "3cF4fDa0a29bc6C0B7848cB06D621Cf6AAA63A18",
                "proxymode": "auto",
                "proxynode": "/bridge"
            },
            "type": "Entertainment"
        },
        "2": {
            "action": {
                "on": false
            },
            "area_id": "f407463b64f34fd4941657f5f36c3564",
            "class": "Other",
            "enabled": true,
            "lights": [],
            "name": "",
            "sensors": [],
            "state": {
                "all_on": true,
                "any_on": false
            },
            "type": "Room"
        },
        "3": {
            "action": {
                "on": false
            },
            "area_id": "f8fb204853fc4dda9788a77326f92c6a",
            "class": "Other",
            "enabled": true,
            "lights": [],
            "name": "",
            "sensors": [],
            "state": {
                "all_on": true,
                "any_on": false
            },
            "type": "Room"
        },
        "4": {
            "action": {
                "on": false
            },
            "area_id": "47f79949044844cc8dfa1ee3c98d1488",
            "class": "Other",
            "enabled": true,
            "lights": [],
            "name": "",
            "sensors": [],
            "state": {
                "all_on": false,
                "any_on": false
            },
            "type": "Room"
        },
        "5": {
            "action": {
                "on": false
            },
            "area_id": "17e72335989f47b7af9921b9190b6669",
            "class": "Other",
            "enabled": true,
            "lights": [],
            "name": "",
            "sensors": [],
            "state": {
                "all_on": true,
                "any_on": false
            },
            "type": "Room"
        },
        "6": {
            "action": {
                "on": false
            },
            "area_id": "9ccdae7e25f9476f8a9230e70a04c3e2",
            "class": "Other",
            "enabled": true,
            "lights": [],
            "name": "",
            "sensors": [],
            "state": {
                "all_on": false,
                "any_on": false
            },
            "type": "Room"
        },
        "7": {
            "action": {
                "on": false
            },
            "area_id": "122c00456b3d423a985a3a7ce493a42c",
            "class": "Other",
            "enabled": true,
            "lights": [],
            "name": "",
            "sensors": [],
            "state": {
                "all_on": true,
                "any_on": false
            },
            "type": "Room"
        },
        "8": {
            "action": {
                "on": false
            },
            "area_id": "5c5ac314ef334c3392cefddea414af2e",
            "class": "Other",
            "enabled": true,
            "lights": [],
            "name": "",
            "sensors": [],
            "state": {
                "all_on": false,
                "any_on": true
            },
            "type": "Room"
        },
        "9": {
            "action": {
                "on": false
            },
            "area_id": "9c62531140d845d4b18b0b39e5a3e2a9",
            "class": "Other",
            "enabled": true,
            "lights": [],
            "name": "",
            "sensors": [],
            "state": {
                "all_on": false,
                "any_on": false
            },
            "type": "Room"
        }
    },
    "lights": {
        "1": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.etagere",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:33:aa:83:c7:eb:e3:30-bc"
        },
        "10": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.reading_lamp",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:6e:1d:d9:a0:8a:fe:1d-a0"
        },
        "11": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.stars",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:0b:2b:7d:43:51:38:05-f4"
        },
        "12": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.downlight",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:31:f7:13:ae:5e:3a:d5-16"
        },
        "13": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.ne",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:e5:dc:fe:b0:b4:a0:c1-ab"
        },
        "14": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.se",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:dc:76:ab:24:7a:cb:3e-f4"
        },
        "15": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.sw",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:96:15:5a:f1:52:7f:c7-ba"
        },
        "16": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.nw",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:c8:a1:aa:61:61:4b:f4-0b"
        },
        "17": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.left_dining",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:74:11:19:80:16:8e:e7-3a"
        },
        "18": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.right_dining",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:03:a2:4d:8d:90:6e:cc-b9"
        },
        "19": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.left_ambient",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:6f:e3:05:ee:1a:b5:7a-9b"
        },
        "2": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.floor_lamp",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:7e:e4:a5:d2:97:b0:7f-49"
        },
        "20": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.right_ambient",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:dd:10:5f:2e:69:93:c2-a2"
        },
        "21": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.rear_ambient",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:93:39:2e:70:20:9c:38-2e"
        },
        "22": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.dining_room",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:05:67:00:e6:15:5b:f9-f7"
        },
        "23": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.nightstand",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:0d:42:5d:b9:4f:a8:65-de"
        },
        "24": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.backlight",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:01:80:56:12:96:d6:e9-33"
        },
        "3": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.bias",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:d2:f4:ae:93:38:d3:ac-b6"
        },
        "4": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.right_nightstand",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:09:bf:7f:a6:02:d0:ca-99"
        },
        "5": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.left_nightstand",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:ad:67:c5:dc:47:33:65-23"
        },
        "6": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.ceiling_fan",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:5f:53:5e:f3:e6:32:f2-4d"
        },
        "7": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.foyer",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:b8:f5:86:3f:25:02:af-b2"
        },
        "8": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.shop_light",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:bb:a9:e7:0d:88:06:88-5d"
        },
        "9": {
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": true,
                    "mode": "safety"
                }
            },
            "enabled": true,
            "entity_id": "light.lightstrip",
            "name": "",
            "throttle": 0,
            "uniqueid": "00:2a:76:06:a8:d8:ac:2f-ac"
        }
    },
    "resourcelinks": {
        "1": {
            "classid": 10081,
            "description": "Restore state after streaming",
            "links": [
                "/groups/14",
                "/rules/1",
                "/rules/2",
                "/scenes/1"
            ],
            "name": "Restore state after streaming"
        },
        "2": {
            "classid": 10081,
            "description": "Restore state after streaming",
            "links": [
                "/groups/15",
                "/rules/3",
                "/rules/4",
                "/scenes/2"
            ],
            "name": "Restore state after streaming"
        },
        "3": {
            "classid": 10081,
            "description": "Restore state after streaming",
            "links": [
                "/groups/16",
                "/rules/5",
                "/rules/6",
                "/scenes/3"
            ],
            "name": "Restore state after streaming"
        }
    },
    "rules": {
        "1": {
            "actions": [
                {
                    "address": "/scenes/1",
                    "body": {
                        "storelightstate": true
                    },
                    "method": "PUT"
                }
            ],
            "conditions": [
                {
                    "address": "/groups/14/stream/active",
                    "operator": "eq",
                    "value": "true"
                }
            ],
            "name": "Store state",
            "recycle": true
        },
        "2": {
            "actions": [
                {
                    "address": "/groups/14/action",
                    "body": {
                        "scene": "1"
                    },
                    "method": "PUT"
                }
            ],
            "conditions": [
                {
                    "address": "/groups/14/stream/active",
                    "operator": "eq",
                    "value": "false"
                }
            ],
            "name": "recall stored state when ent end",
            "recycle": true
        },
        "3": {
            "actions": [
                {
                    "address": "/scenes/2",
                    "body": {
                        "storelightstate": true
                    },
                    "method": "PUT"
                }
            ],
            "conditions": [
                {
                    "address": "/groups/15/stream/active",
                    "operator": "eq",
                    "value": "true"
                }
            ],
            "name": "Store state",
            "recycle": true
        },
        "4": {
            "actions": [
                {
                    "address": "/groups/15/action",
                    "body": {
                        "scene": "2"
                    },
                    "method": "PUT"
                }
            ],
            "conditions": [
                {
                    "address": "/groups/15/stream/active",
                    "operator": "eq",
                    "value": "false"
                }
            ],
            "name": "recall stored state when ent end",
            "recycle": true
        },
        "5": {
            "actions": [
                {
                    "address": "/scenes/3",
                    "body": {
                        "storelightstate": true
                    },
                    "method": "PUT"
                }
            ],
            "conditions": [
                {
                    "address": "/groups/16/stream/active",
                    "operator": "eq",
                    "value": "true"
                }
            ],
            "name": "Store state",
            "recycle": true
        },
        "6": {
            "actions": [
                {
                    "address": "/groups/16/action",
                    "body": {
                        "scene": "3"
                    },
                    "method": "PUT"
                }
            ],
            "conditions": [
                {
                    "address": "/groups/16/stream/active",
                    "operator": "eq",
                    "value": "false"
                }
            ],
            "name": "recall stored state when ent end",
            "recycle": true
        }
    },
    "scenes": {
        "1": {
            "group": "14",
            "name": "entertainment recover scene",
            "recycle": true,
            "type": "GroupScene"
        },
        "2": {
            "group": "15",
            "name": "entertainment recover scene",
            "recycle": true,
            "type": "GroupScene"
        },
        "3": {
            "group": "16",
            "name": "entertainment recover scene",
            "recycle": true,
            "type": "GroupScene"
        }
    },
    "users": {
       }
    }
}

**Comment by cdhmri5** [comment]
is this going to be addressed? i assume the issue isn't on my end. how much focus is being placed on entertainment areas in the current development cycle? is it always going to be experimental?

**Comment by alexyao2015** [comment]
Try the dev version and see if the issue is resolved.

**Comment by cdhmri5** [comment]
it worked instantly. thanks! i hope this makes it into stable soon.
