### ISSUE TITLE
Crashes on start up

### ISSUE THREAD

**Issue by JackRonan** [hass-emulated-hue/core#156]
'''
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-set-vars.sh: executing... 
[cont-init.d] 00-set-vars.sh: exited 267.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
'''
I'm getting this error during start up, I'm using Home Assistant on a Raspberry Pi Zero W. Is there anyway to find out more specifically what is going wrong?

**Comment by alexyao2015** [comment]
The rpi zero doesn't have enough resources to run it.
