### ISSUE TITLE
Switch in HUE

### ISSUE THREAD

**Issue by Lip90** [hass-emulated-hue/core#161]
Hello,

I have the following problem. The Home Asstant standard HUE emulation no longer works in my opinion. You can add devices, but you cannot assign the devices to rooms. No matter what I try, it doesn't work.

With your software it works without any problems. Unfortunately, I can't use sockets here. I use the innr sockets because they can also measure the current Power and would like to control my devices via Alexa without having to pay for the cloud. I just want the device like e.g. Switch the PC on and off or switch the office on (however, this is not possible with the Emulated Hue, as I said).

Thanks in advance.

**Comment by alexyao2015** [comment]
What exactly are you using sockets for? Current power??

**Comment by Lip90** [comment]
I use it to switch my tv, pc and server. the innr switches can measure the current power consumption.

Am 11.06.2021 um 14:07 schrieb Alex ***@***.***>:

﻿

What exactly are you using sockets for? Current power??

**Comment by alexyao2015** [comment]
Its very unlikely that this would ever be implemented without a PR of sorts. The use case seems limited and time to implement such a feature would be too great.

**Comment by Lip90** [comment]
the only function I would like is to turn on and off sockets. is that possible and easy to implement?

Am 11.06.2021 um 14:23 schrieb Alex ***@***.***>:

﻿

Its very unlikely that this would ever be implemented without a PR of sorts. The use case seems limited and time to implement such a feature would be too great.

**Comment by alexyao2015** [comment]
As mentioned, no it is not easy to implement as it is the core of the application. I'll be closing this since the use case is limited and definitely not a common request.

**Comment by stanwebber** [comment]
control switches as lights in ha which emulated hue can then pick up: https://www.home-assistant.io/integrations/light.switch/
