### ISSUE TITLE
Lights not detected in iLightShow app

### ISSUE THREAD

**Issue by simplenotezy** [hass-emulated-hue/core#163]
**Describe the bug**
When using the app iLightShow no lights are detected.

**Steps to Reproduce**
1. Download iLightShow on app store
2. Add the bridge. Enable link mode
3. Once connected, the app will say "No light detected"

THIS IS VERY IMPORTANT TO KNOW TO BE ABLE TO FIX THE BUG!
If at all possible, please try to create reproduction steps from
a clean environment (delete all existing config and reinstall from
scratch). Again, please make sure to read all primers to ensure we 
are able to help you.
-->

**Expected behavior**
Light show show up

**Logs**

**Hardware Info:**
 - Architecture (Ex: x86, ARM): 
 - Addon version (Ex: stable or dev): latest
 - OS (Ex: Windows 10, Ubuntu Buster): iOS, latest
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Raspberry pi 3+

**Additional context**
It used to work fine when using the Phillips Hue Bridge. I can say that my Phillips Hue TV Abilight+hue integration works great, it's only this app where it's not working.

It could be that the lights should be exposed in a special way, but I don't know.

**Comment by alexyao2015** [comment]
There is a chance it's using the v2 api, and if that's the case, it's unlikely it will be supported soon.

**Comment by simplenotezy** [comment]
I see. What version of the API is the emulater using?

**Comment by alexyao2015** [comment]
The v2 api just recently got released along with the new hue app. Its undocumented still and unfortunately I have no devices available to infer the API from, making implementation tough. This uses the v1 api.

**Comment by alexyao2015** [comment]
Just downloaded the app. It seems that all lights are detected fine.

**Comment by alexyao2015** [comment]
Gave this another try today. Previously this app did work, but it appears that a recent update to it has caused it to no longer work. Lights appear perfectly fine for me, however, all effects do not work in either legacy or entertainment mode. 

During entertainment mode (once packet size is corrected, normally not an issue), it appears to continually start and stop entertainment mode as if its waiting for a response from the bridge. 
During legacy mode, it appears that requests are continually being made to the groups api, but its not doing anything further as if it is receiving an incorrect response. 

Would need some input from the app developer to act further.

**Comment by alexyao2015** [comment]
Hey @nicolasanjoran are you able to comment on the reason for the issues above?

**Comment by alexyao2015** [comment]
Retested and both modes actually do work. This app validates ssl certificates displayed so if your certificates are wrong, it will fail and exhibit the same symptoms mentioned aboved.

**Comment by alexyao2015** [comment]
You'll need to ensure the bridge is accessible through standard http/s ports (80 and 443). These cannot be changed. Additionally, when accessing the bridge, it should not show a letsencrypt certificate, but rather one issued from and to your host mac address. All this is typically done automatically when installed as an addon
