### ISSUE TITLE
Hue App asking for update

### ISSUE THREAD

**Issue by GChristoson** [hass-emulated-hue/core#165]
**Describe the bug**

Same as previous issue #33, the official app is asking for an update.

**Steps to Reproduce**
1. Fresh setup using 0.2.6
2. Successfully pair hub in official Hue app
2. Hue app asks to update and fails.

**Comment by alexyao2015** [comment]
Please refer to this https://github.com/hass-emulated-hue/core/discussions/104#discussioncomment-929702

**Comment by alexyao2015** [comment]
You can use alternative apps like hue essentials which will still continue to function as normal.
