### ISSUE TITLE
ZigBee lights are only added as on/off and not as dimmable lights

### ISSUE THREAD

**Issue by carsten-h** [hass-emulated-hue/core#184]
**Describe the bug**

I installed the Addon as described and I added the „Hue hub“ to my Harmony Hub.
But when I try to control eg. a ZigBee light via the Harmony hub I can only switch the light on and off. There is no possibility to control the brightness or color although it should be possible. 

**Steps to Reproduce**

**Expected behavior**

Lights should have all possibilities inside the „Hue Hub“.

**Logs**

**Hardware Info:**
 - Architecture (Ex: x86, ARM): ARM
 - Addon version (Ex: stable or dev): 0.2.7
    - Value of "tag_commit_or_branch" if using dev: 
 - OS (Ex: Windows 10, Ubuntu Buster): Home Assistant Operating System
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Raspberry Pi 4

**Additional context**

![60209B6D-8740-44BD-8836-F953486DFCE5](https://user-images.githubusercontent.com/44360828/128424111-9df70436-4dcc-4f12-9393-39b2f4d7c904.jpeg)

![1968DC44-4677-4851-8A9A-405281E27344](https://user-images.githubusercontent.com/44360828/128424302-c600fff0-7820-40e6-9d0c-a42baded75b8.jpeg)

**Comment by alexyao2015** [comment]
Please provide the attributes information under developer tools of the light

**Comment by carsten-h** [comment]
> Please provide the attributes information

I added them directly into the issue.

**Comment by alexyao2015** [comment]
Try the dev addon

**Comment by carsten-h** [comment]
> Try the dev addon

Yes, this is working like a charm!
Thank you very much for the solution!

Is it possible to get some switchable sockets or other devices to the Hue devices? Or isn‘t that possible.

**Comment by alexyao2015** [comment]
#172

**Comment by alexyao2015** [comment]
Will be pushing the changes from dev to release in the next week

**Comment by carsten-h** [comment]
Thank you very much!
