### ISSUE TITLE
Hue app (iOS) - doesnt work

### ISSUE THREAD

**Issue by jlukas99** [hass-emulated-hue/core#201]
Hi,

After connecting bridge with my hue app i have all time information "connecting..."

restart app and reconnecting bridge does not slove problem

Hue essentials app work fine but official hue app doesnt

![IMG_5666](https://user-images.githubusercontent.com/21359179/132464983-b0ec2654-3238-4a31-8bf0-54368ca9e255.PNG)

**Comment by alexyao2015** [comment]
#104
