### ISSUE TITLE
First screen 'making connection' stuck after connecting first time

### ISSUE THREAD

**Issue by tiestofan9** [hass-emulated-hue/core#229]
Hi all,

At the moment I installed this integration a few times on HA core-2021.11.1 and I keep having the same problem; after following the instructions, connecting to the virtual Hue bridge, the Hue app on iOS 15 keeps on 'trying to connect'. 

I'm really clueless. Can someone help me on this issue? Thanks a lot!
![IMG_A265FB3083B1-1](https://user-images.githubusercontent.com/74556472/140959019-daecfb04-9434-410f-aaa7-7e51e1e0a129.jpeg)

**Comment by alexyao2015** [comment]
#104
