### ISSUE TITLE
Mandatory Update for Hue Bridge

### ISSUE THREAD

**Issue by sheminasalam** [hass-emulated-hue/core#237]
I have installed the addon in my home assistant supervised installation in rpi4. Then I have installed the official philips hue app on my iphone and tried to add the device. The hue hub was discovered but I am not able to use an update window which fails when I try to update.
![msg408344267-117586](https://user-images.githubusercontent.com/45196177/142790406-bde2da34-bef6-4634-b712-d2169d5e1976.jpg)

![photo1637546802](https://user-images.githubusercontent.com/45196177/142790532-093aef06-2b41-4e97-8ad2-8d240f2ec995.jpeg)

**Comment by way2many** [comment]
Haha yes, spent countless of hours to install nginx, configure the docker containers of nginx, homeassistant and hass-emulated-core to make everything work and just to be greeted with a mandatory update which of course is impossible to perform.

I wouldn't categorize this issues as bug though. Hope an easy fix can be implemented.

**Comment by alexyao2015** [comment]
The app requires the v2 api which hasn't been implemented. Other hue apps such as hue essentials work.

Duplicate of #104 and #228

**Comment by sheminasalam** [comment]
hi there is there nay timeline on v2 api

**Comment by adamburgoyne** [comment]
Also interested in this post. Hue Essentials links directly to my Conbee so I have no need to use emulated-hue for that but was hoping to move back to the Hue app for family members.
