### ISSUE TITLE
Phillips App mandatory hub update after pairing

### ISSUE THREAD

**Issue by Pandobear** [hass-emulated-hue/core#240]
**Describe the bug**

**Steps to Reproduce**

**Expected behavior**

**Logs**

**Hardware Info:**
 - Architecture (Ex: x86, ARM): 
 - Addon version (Ex: stable or dev): 
    - Value of "tag_commit_or_branch" if using dev: 
 - OS (Ex: Windows 10, Ubuntu Buster): 
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): 

**Additional context**

**Comment by Pandobear** [comment]
Sorry, description of issue is 

run integration
pair with Phillips hue app works fine
Philips hue app reports mandatory software update required - and fails if you accept it.
bypassing by selecting other hub (actual phillips one) allows you to view the software version of HA hub as 1946157000

**Comment by Pandobear** [comment]
So it seems that we need to be able to update the version number of the emulated hub beyond the 1946157000 to be able to add new hubs currently.  Is there an easy way to do that?

**Comment by alexyao2015** [comment]
#214
