### ISSUE TITLE
Latest swversion checker isn't working

### ISSUE THREAD

**Issue by mattyway** [hass-emulated-hue/core#249]
**Describe the bug**

The Github Action that checks for the latest swversion is not detecting the latest swversion correctly. It seems like the format on the Hue bridge release notes page has changed.

**Steps to Reproduce**
1. Go to the Hue Bridge release notes page: https://www.philips-hue.com/en-au/support/release-notes/bridge
2. See that the latest version is `1948086000` (as of 26/12/2021)
3. Go to a recent run of the `Update swversion` Github action, eg: https://github.com/hass-emulated-hue/core/runs/4634019533
4. Click to expand the `Update` step
5. See that the action has reported `1946157000` as the latest version

**Expected behavior**

The `Update swversion` Github action reports the correct latest version (as of 26/12/2021 that is `1948086000`)

**Additional context**

It seems like the logic [here](https://github.com/hass-emulated-hue/update-swversion-action/blob/42b2cfa6f1c3dfc575c8a48159725e38c44a9f1f/src/main.py#L23:L44) needs to be modified to expect the new format on the release notes page. It looks like versions released after the v1 Bridge support was dropped don't mention `(Hue Bridge v2)`

**Comment by alexyao2015** [comment]
Thanks for the report. Unfortunately, with how web scraping works, it's always bound to break. With that said, I'm not sure how much of an impact swversion has on apps at the moment. The official hue app does not work at the moment due to usage of the v2 api, and that is the only app that I know of that actually checks the swversion.

**Comment by Ricardo1320-del** [comment]
manual adjustment of definitions.json also does not work. After a reboot, everything will be reverted to the old one.

This comes from a official Hue Bridge:

{"name":"Philips hue","datastoreversion":"113","swversion":"1948086000","apiversion":"1.48.0","mac":"00:17:88:47:ff:0e","bridgeid":"001788FFFE47FF0E","factorynew":false,"replacesbridgeid":null,"modelid":"BSB002","starterkitid":""}

Maybe you can use it?

**Comment by Bubbgump209** [comment]
Editing definitions.json will simply get overwritten on restart from the docker image. I'm currently making a new image from the current image as a work around and will report back.

**Comment by Bubbgump209** [comment]
Pull request here v]https://github.com/hass-emulated-hue/core/pull/255

**Comment by alexyao2015** [comment]
Again, the official hue app still will not work given an updated swversion. Updating it is not an issue, but I'm not sure what issue it will solve.

P.S. The dev addon will allow you to test the PR changes yourself before it is merged.

**Comment by alexyao2015** [comment]
#214 for reference

**Comment by Bubbgump209** [comment]
> P.S. The dev addon will allow you to test the PR changes yourself before it is merged.

Good to know. Let me play a bit. It seems you don't have a V2 hub? Would you want one donated?

**Comment by Ricardo1320-del** [comment]
> > P.S. The dev addon will allow you to test the PR changes yourself before it is merged.
> 
> Good to know. Let me play a bit. It seems you don't have a V2 hub? Would you want one donated?

Can you tell me, how can i update the dev with correct sw version for a test?

**Comment by alexyao2015** [comment]
@Ricardo1320-del See [here](https://github.com/hass-emulated-hue/hassio-repo/blob/master/emulated_hue_dev/DOCS.md#option-tag_commit_or_branch). This would be easiest to set if you were running as an addon where config options can easily be set.

@Bubbgump209 That would be quite helpful if you had one extra! Feel free to email me at myusername (at) gmail (dot) com. (Typed like that to hopefully avoid automated spam bots😄).

**Comment by botioni** [comment]
seme here not working mandatory update

**Comment by alexyao2015** [comment]
The swversion checker was fixed back in july so closing.

**Comment by botioni** [comment]
Not working if it was fixed then now is broken
