### ISSUE TITLE
Hue App request bridge update with last version

### ISSUE THREAD

**Issue by macfr76** [hass-emulated-hue/core#268]
**Describe the bug**
When trying to add the Fake Hue Bridge, Hue App ask to update.

**Steps to Reproduce**
Just add the home assistant hue bridge

After it fails, if you check in settings :
- a regular hue bridge has version in this format : 1.49.1949203030
- home assistant emulated hue has a wrong format : 1946157000

**Expected behavior**
hass emulated hue should update itself the faxe version number or offer a way to change it manually

**Hardware Info:**
 - Architecture (Ex: x86, ARM): ARM64
 - Addon version (Ex: stable or dev): 
    - Home Assistant 2022.2.0
    - Emulated HUE (0.2.13)
 - OS (Ex: Windows 10, Ubuntu Buster): Home Assistant OS 7.2
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): RPI 4

**Comment by alexyao2015** [comment]
#257
