### ISSUE TITLE
Using with conainer version of home assistant fails with "Invalid access token or password"

### ISSUE THREAD

**Issue by lweberru** [hass-emulated-hue/core#272]
**Describe the bug**
I am using home assistant and also this hass-emulated-hue container as docker-compose variant. The connection from this container to my home assistant fails on startup with: 
`hass_client.exceptions.AuthenticationFailed: Invalid access token or password`

I created a long living token within home-assistant and pasted the code into the "HASS_TOKEN" var.

**Steps to Reproduce**

1. Install and start home assistant via docker-compose
2. Generate long living token in home assistants profile
3. Install hass-emulated-hue via docker-compose and add hass token there
My docker-compose for this container looks like this:

```
  emulated-hue:
    container_name: emulated-hue
    network_mode: host
    privileged: true
    logging:
      driver: journald
    restart: always
    environment:
      - TZ=Europe/Berlin
      - HASS_TOKEN="<my-token>"
      - HASS_URL=http://192.168.1.153:8123
#      - VERBOSE=true
    image: ghcr.io/hass-emulated-hue/core:latest # <<< Desired release version here
    volumes:
      - /home/pi/HomeAssistant/config/emulated-hue:/config/.emulated-hue
```

4. start hass-emulated-hue

**Expected behavior**

A working hue emulation

**Logs**

in emulated-hue
```
[09:36:43] INFO: Starting Emulated Hue...
2022-02-14 09:36:43,866 INFO  emulated_hue.config -- Auto detected listen IP address is 192.168.1.153
2022-02-14 09:36:43,932 ERROR asyncio -- Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.9/site-packages/aiorun.py:221> exception=AuthenticationFailed('Invalid access token or password')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiorun.py", line 231, in new_coro
    await coro
  File "/app/emulated_hue/__init__.py", line 56, in async_start
    await self._hass.connect()
  File "/usr/local/lib/python3.9/site-packages/hass_client/client.py", line 250, in connect
    raise AuthenticationFailed(
hass_client.exceptions.AuthenticationFailed: Invalid access token or password
```
and in home assistant:
```
2022-02-14 09:36:43 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from hassio (192.168.1.153). (Python/3.9 aiohttp/3.8.1)
```

**Hardware Info:**
 - Architecture (Ex: x86, ARM): ARM
 - Addon version (Ex: stable or dev): latest
 - OS (Ex: Windows 10, Ubuntu Buster): Raspbian GNU/Linux 10 (buster)
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Raspberry PI 4

**Additional context**

**Comment by lweberru** [comment]
If I curl with the same token It seems to work:
```
curl -s -I -X GET http://192.168.1.153:8123/config/dashboard -H 'Authorization: Bearer <my-token>'
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 9331
Date: Mon, 14 Feb 2022 09:17:43 GMT
Server: Python/3.9 aiohttp/3.8.1

```

**Comment by lweberru** [comment]
I changed to image version to 0.2.9 and removed the quotation marks surrounding the HASS_TOKEN and needed to ensure, that the URL does not end with a "/" and also without quoation marks. Now my hue app can connect. But tries to update the hub, which fails as expected. Further use is because of this try to update not possible

**Comment by alexyao2015** [comment]
See the two pinn issues

**Comment by alexyao2015** [comment]
Closing due to no response
