### ISSUE TITLE
Disable Pairing Notification

### ISSUE THREAD

**Issue by swamplynx** [hass-emulated-hue/core#281]
**Is your feature request related to a problem? Please describe.**

**Describe the feature that you would like to be added**

Configuration switch to disable pairing notifications.

**Describe alternatives you've considered**

I've check for this option in the existing config.

**Describe your use case for this feature**

I have every client I want paired with the "hub," but I have some other devices on my network that I don't want to pair that do a background discovery for Hue hubs (whether or not you put them into a "look for new devices" scan pattern), so I constantly get notifications in HA to enable pairing.

**Additional context**

**Comment by alexyao2015** [comment]
Interesting. What device are you using that is causing this? Most shouldn't perform background scans, and if they do, shouldn't continually attempt pairing unless requested.

**Comment by swamplynx** [comment]
I "think" it is an Echo, but not sure which one / model. Is there a way to discern a MAC address from the client key? My use case is to control lights with some Brilliant controls and a Harmony that I previously had linked up to SmartThings. Aside from those two, the only other client in my yaml config is the Echo, which I am NOT using it with (or ever have) so I think that is the culprit.

**Comment by alexyao2015** [comment]
In your logs, you should see a post to /API along with a description of the device. That should help you identify it.

**Comment by swamplynx** [comment]
Now that I disconnected the older Echo device that was sending discovery requests, another one of my new Echo's has picked up the cause and is sending unsolicited discovery requests. Note I don't have the Hue skill enabled, nor am I doing a "discover devices' from the Alexa app. Since there is no apparent way to prevent Echo's from sending out unsolicited paring requests, this feature enhancement is needed. Thanks.

```
2022-03-31 12:35:46,666 DEBUG emulated_hue.api -- [192.168.123.63] GET /description.xml
2022-03-31 12:35:46,683 DEBUG emulated_hue.api -- [192.168.123.63] POST /api
2022-03-31 12:35:46,683 DEBUG emulated_hue.api -- {'devicetype': 'Echo'}
2022-03-31 12:35:46,684 INFO  emulated_hue.config -- Link request detected - Use the Homeassistant frontend to confirm this link request. 
```

**Comment by swamplynx** [comment]
Standy by... Just noticed a new "Device Discovery" setting in the Alexa app. I've disabled that now. Let's see if that kills this behavior.

**Comment by swamplynx** [comment]
Update. Even after disabling Discovery in the Alexa app and restarting all my Echo’s they still insist on doing auto-discovery every few hours.

**Comment by alexyao2015** [comment]
Interesting, nothing gets paired? The post to /api and a devicetype field is exactly what the official documentation says to do when pairing. There's no other instance that request should be sent.

**Comment by swamplynx** [comment]
Yep. It's super weird behavior (thanks Amazon). You would think disabling automatic device discovery on the Alexa side would kill that behavior, but alas it does not.
