### ISSUE TITLE
Hue official app ask to update the bridge so it doesn't work

### ISSUE THREAD

**Issue by blasserre** [hass-emulated-hue/core#302]
**Describe the bug**

**Steps to Reproduce**

**Expected behavior**

**Logs**

**Hardware Info:**
 - Architecture (Ex: x86, ARM): 
 - Addon version (Ex: stable or dev): 
    - Value of "tag_commit_or_branch" if using dev: 
 - OS (Ex: Windows 10, Ubuntu Buster): 
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): 

**Additional context**

**Comment by amaisano** [comment]
Same. In the app, I have two bridges. One physical, one from this add-on.

I was able to successfully pair it with Home Assistant, but when I attempt to switch to that hub in the iOS Hue app, a screen appears immediately saying there is a mandatory update.

Physical Bridge:
Software version: `1.52.1952043030`

Addon Bridge:
Software version: `1946157000`

Is it simply a matter of updating the version HA is reporting?

**Comment by alexyao2015** [comment]
#265 
In short, I need to update it but haven't had time to get around to it yet. Hopefully will be able to work on it later this year.
