### ISSUE TITLE
Emulated Hue incompatibility with ZHA or ... ?

### ISSUE THREAD

**Issue by dr3amr** [hass-emulated-hue/core#303]
Just installed today Emulated Hue. I have two Hue RGB bulbs which I disconnected from the Hue Hub to get them in pairing mode, and I added them then to ZHA (through Sonoff Zigbee 3.0 USB Dongle Plus). After installing the Emulated Hue, HA discovers the new Hue Bridge, and I add it as Integration. Problem is, the two Hue RGB bulbs are continuously added to the Hue Bridge integration (currently 2883 devices). Is this issue due ZHA - Emulated Hue or other ? Tried installing the Dev branch of Emulated Hue with same result. How / where can I look to understand this behavior ?

**Comment by alexyao2015** [comment]
Don't add the emulated hub to home assistant as an integration or you will cause a loop as you see there. Will disable the availability to do this in the future to prevent this from occuring.
