### ISSUE TITLE
Add support for Home Assistant update entities in swupdate

### ISSUE THREAD

**Issue by PatrikTheDev** [hass-emulated-hue/core#306]
**Describe the feature that you would like to be added**

Add support for the new [Home Assistant update entities](https://developers.home-assistant.io/blog/2022/03/20/update-entity/)

**Describe your use case for this feature**

It would allow you to easily update your Home Assistant instance and even your devices from the Hue app

This would require us to implement serving a dynamic definition file or at least override parts of it at runtime

**Comment by alexyao2015** [comment]
Going to say the workaround would be to just use a template light atm.
