### ISSUE TITLE
Duplicated devices

### ISSUE THREAD

**Issue by Barml** [hass-emulated-hue/core#316]
**Describe the bug**
Following normal installation (on OS) and pairing, during the discovery Emulated hue has found 821devices/820entities from only two lights.

**Steps to Reproduce**
The steps to reproduce are the normal installation instructions with no deviation. Used stable

**Expected behavior**
First onboarding and set up. Followed install and "pairing", instructions. Discovery opened for 5 minutes and lights to be brought into emulated bridge

**Logs**
'''Logger: homeassistant.components.light
Source: helpers/entity_platform.py:620
Integration: Light (documentation, issues)
First occurred: 16 July 2022 at 22:20:22 (2 occurrences)
Last logged: 16 July 2022 at 22:20:22

Platform hue does not generate unique IDs. ID 00:80:16:b0:fa:44:39:7a-33 already exists - ignoring light.owl_light_411
Platform hue does not generate unique IDs. ID 00:20:44:eb:5b:a4:10:6c-3a already exists - ignoring light.landing_light_410'''

**Hardware Info:**
 - Generic x86
 - Stable
 - Linux
 - X86_64

**Additional context**
This install is to replace a physical bridge. I have replicated the issue twice. First with the actuall hue bridge paired (which duplicated everything paired to that bridge (created 1000's). Second, with the physical bridge integration removed and only using Emulated (I have only two lights directly paired to HA, one generic ZigBee bulb, connecting over Zigbee2MQTT & one switch configured as bulb from Shelly integration). All devices are on Overview dashboard and cannot be switched or deleted via the UI

**Comment by alexyao2015** [comment]
Do not add the bridge to home assistant as an integration. Simply install the addon and use it as is.
