### ISSUE TITLE
0.2.3 crashes during startup 

### ISSUE THREAD

**Issue by dcmeglio** [hass-emulated-hue/core#342]
**Describe the bug**

Latest version crashes on startup. 

**Steps to Reproduce**

1. run 0.2.3

**Expected behavior**

**Logs**

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
cont-init: info: /etc/cont-init.d/20-install.sh exited 2
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Hardware Info:**
 - Architecture (Ex: x86, ARM):  rpi haos
 - Addon version (Ex: stable or dev): 0.2.3
    - Value of "tag_commit_or_branch" if using dev: 
 - OS (Ex: Windows 10, Ubuntu Buster): haos
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): rpi4

**Additional context**

**Comment by alexyao2015** [comment]
From those logs, you appear to be using the dev addon. I can guess you likely have you branch set incorrectly, however you haven't specified it.

If you are using `refactor`, change it to be `master`.

**Comment by dcmeglio** [comment]
Ah refactor was merged into master?

**Comment by alexyao2015** [comment]
Yeah it was done pretty recently in #339. I've been running it for months now and haven't had any issues. I plan on doing some work towards the v2 api sometime soonish.

**Comment by dcmeglio** [comment]
Fixed using master. Other than the random issue I mentioned where the config blanked out a couple times, I agree been running refactor for months just fine.
