### ISSUE TITLE
Connecting to HUE app fails because of mandatory update

### ISSUE THREAD

**Issue by StumblingGamer** [hass-emulated-hue/core#362]
**Describe the bug**

 When setting this up, it seems to work great.  I can use this emulator with 3rd party hue apps such as hueDisco or hueManic. 
 When attempting to link this emulated hub with the official hue app:
[x] Finds the hub
[x] App prompts for button push -> button push works
[x] App then says, there is a mandatory update for this hub (which obviously fails), and because it's mandatory... no bueno. 

I don't think this is a bug on your part, or... even something that you can "fix", but I just wanted you to be aware in case there is a possible workaround. 

**Steps to Reproduce**

**Expected behavior**

**Logs**

**Hardware Info:**
 - Architecture (Ex: x86, ARM): 
 - Addon version (Ex: stable or dev): 
    - Value of "tag_commit_or_branch" if using dev: 
 - OS (Ex: Windows 10, Ubuntu Buster): 
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): 

**Additional context**

**Comment by alexyao2015** [comment]
#257
