### ISSUE TITLE
Official Hue App hangs on time zone selection

### ISSUE THREAD

**Issue by marcushallett** [hass-emulated-hue/core#390]
### Description

When attempting to configure the official Hue app, it reaches a page asking for the time zone. When touching the time zone selection button, a blank white dialog opens with neither text nor buttons of any time zone.

### Expected behavior

Configure device as is normal.

### Reproduction steps

Open Hue app.
Connect to "Bridge"
Time zone dialog appears that cannot be bypassed.
Touch time zone selection button.
Blank modal appears. No further action possible.

Occurs on the Hue App (all versions 4.0 and above, tested on jailbroken device so as to force downgrades) on iOS and the latest version of the Android app.

### Relevant log output

```shell
No relevant log data.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Version

dev

### Dev Version

master

**Comment by alexyao2015** [comment]
This is essentially #257. The official hue app isn't going to work until the v2 api is implemented.

**Comment by marcushallett** [comment]
is it possible to manually create an entertainment mode group?

**Comment by marcushallett** [comment]
Also, I understand this is caused by the same issue #257, but seeing as the behavior the user experiences is different, closing as a duplicate may result in others who experience the same issue opening further duplicates. We all know that people usually won't read closed issues before creating a new one.
