### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by cronner** [hass-emulated-hue/core#391]
### Description

Log only says: s6-overlay-suexec: fatal: can only run as pid 1

looks like it's starting but suddenly stops.

### Expected behavior

start without error

### Reproduction steps

install 3.0 and start

### Relevant log output

```shell
s6-overlay-suexec: fatal: can only run as pid 1
```

### Operating system

HassOS

### Install method

HassOS Addon

### Version

3.0

**Comment by alexyao2015** [comment]
Thanks for reporting. This should be fixed now. You may need to uninstall, check for updates, and reinstall to make it work again. Nothing should be lost when doing so.

**Comment by cronner** [comment]
It's working now, thanks :)
