### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by smartmatic** [hass-emulated-hue/core#409]
### Description

I‘ve installed emulated hue to integrate the new generation of Rithum smart switch and used this guideline:

https://github.com/finopsfuntimes/core/blob/master/README.md

Now the below error is flooding my logs:

Error doing job: Task exception was never retrieved

Diagnostics
[config_entry-hue-e23f7155a3532b41ec0e99634c6374b8.json.txt](https://github.com/hass-emulated-hue/core/files/10777486/config_entry-hue-e23f7155a3532b41ec0e99634c6374b8.json.txt)

### Expected behavior

Get rid of this error.

### Reproduction steps

Not possible at the moment

### Relevant log output

```shell
Logger: homeassistant
Source: components/hue/v1/light.py:352 
First occurred: 13:03:09 (1546 occurrences) 
Last logged: 15:11:56

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/components/hue/v1/light.py", line 285, in async_update_items
    current[item_id] = create_item(api, item_id)
  File "/usr/src/homeassistant/homeassistant/components/hue/v1/light.py", line 128, in create_light
    return item_class(
  File "/usr/src/homeassistant/homeassistant/components/hue/v1/light.py", line 352, in __init__
    self.is_livarno = light.manufacturername.startswith("_TZ3000_")
AttributeError: 'NoneType' object has no attribute 'startswith'
```

### Operating system

HassOS

### Install method

HassOS Addon

### Version

0.3.0

### Dev Version

0.3.0

**Comment by alexyao2015** [comment]
It seems like you are running a custom version from the linked readme. If this is true, I will be unable to provide support. However, glancing at the logs it appears that it's coming from the built in hue component in home assistant. Make sure you did not try to add the emulated bridge to home assistant.

**Comment by smartmatic** [comment]
Actually i've added emulated hue as second bridge besides the original Philips Hue bridge. Removed emulated Hue from integrations and error seems to be removed. 
Ticket can be closed! 
Thank you

**Comment by alexyao2015** [comment]
This is why reproduction steps are crucial. I will be closing any new tickets without them.
