### ISSUE TITLE
Entities filtering

### ISSUE THREAD

**Issue by Mk4242** [hass-emulated-hue/core#46]
Hi,

In my use case I'd like family members to control a limited subset of all HA-managed lights, couldn't find a way to whitelist/blacklist entities as I understand all entities from the light domain are by default exposed to the emulated hue.  Would be a great feature to add if not available. 

Cheers!

F.

**Comment by marcelveldt** [comment]
you can delete rooms/lights from the hue app and they won't show up again

**Comment by alexyao2015** [comment]
I think this is something we'll need to work on in the future, but for now, deleting things from the hue app will work.

**Comment by marcelveldt** [comment]
In your Home Assistant config directory you'll find a folder called emulated_hue.
Edit the file emulated_hue.json and you can disable lights and/or rooms from showing up in emulated hue.

You can also do this in the Hue app itself by just deleting a light.
Eventually there will be some sort of nice GUI way to configure this.
