### ISSUE TITLE
Deleted/Changed entities result in entities that are no longer exposed.

### ISSUE THREAD

**Issue by M-See** [hass-emulated-hue/core#477]
### Description

If you change the list of exposed entities or delete entities in the configuration.yaml, some previously functioning entities are suddenly no longer recognised/working with the error "Entity not exposed: number XY".

This seems to be because the emulated_hue.ids in the /config/storage folder is NOT adjusted/overwritten according to the changed configuration.yaml script. One must then manually delete the no longer existing entities from the emulated_hue.ids so that entities are exposed and recognised again at all.

### Expected behavior

It would be good if the *.ids file was updated accordingly.

### Reproduction steps

See this thread for details: [HA-Community](https://community.home-assistant.io/t/emulated-hue-entity-not-found-but-entity-not-in-yaml-anymore/319645/28)

### Relevant log output

```shell
2021-10-28 08:27:49 ERROR (MainThread) [homeassistant.components.emulated_hue.hue_api] Entity not exposed: 12
```

### Operating system

HassOS

### Install method

HassOS Addon

### Version

V2

**Comment by alexyao2015** [comment]
This seems related to the built in home assistant emulated hue component which is unrelated to this emulated hue addon.
