### ISSUE TITLE
Still alive or dead?

### ISSUE THREAD

**Issue by KeviinCosmos** [hass-emulated-hue/core#503]
### Description

No updates since January? Is this addon dead?

### Expected behavior

Question of survival 

### Reproduction steps

Is it still in production?

### Relevant log output

```shell
Not much
```

### Operating system

HassOS

### Install method

HassOS Addon

### Version

3.0.0

### Any other information that may be helpful

Is this still in development?

**Comment by jsenecal** [comment]
Please have a read at https://github.com/hass-emulated-hue/core/discussions/228

**Comment by cibrenvenuti** [comment]
Please, keep It alive!
