### ISSUE TITLE
"Pairing with Home Assistant is explicitly disabled"

### ISSUE THREAD

**Issue by tarheelz** [hass-emulated-hue/core#508]
### Description

Logs now return a message that pairing an Hue Emulation Bridge with Home Assistant is explicitly disabled.

### Expected behavior

Successful pairing.

### Reproduction steps

Once initially paired (and after escaping from the mandated update that has been noted in other tickets), any opening of the Hue app or attempt to pair from Home Assistant triggers this error.

### Relevant log output

```shell
Logger: homeassistant.components.hue.config_flow
Source: components/hue/config_flow.py:178
Integration: Philips Hue (documentation, issues)
First occurred: 2:48:26 PM (11 occurrences)
Last logged: 2:52:21 PM

Unknown error connecting with Hue bridge at 192.168.1.221
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hue/config_flow.py", line 178, in async_step_link
    app_key = await create_app_key(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohue/util.py", line 50, in create_app_key
    raise exc
  File "/usr/local/lib/python3.11/site-packages/aiohue/util.py", line 46, in create_app_key
    raise_from_error(result["error"])
  File "/usr/local/lib/python3.11/site-packages/aiohue/errors.py", line 42, in raise_from_error
    raise cls(error["description"])
aiohue.errors.AiohueException: Pairing with Home Assistant is explicitly disabled
```

### Operating system

HassOS

### Install method

HassOS Addon

### Version

Current version: 0.3.0

### Any other information that may be helpful

Sorry gang.  This looks like bad news.  Please let me know if I can help in any way.  (I also have a Gen 2 square bridge if that matters.)

**Comment by alexyao2015** [comment]
You're not supposed to pair the emulator with home assistant or it will loop infinitely, thus pairing with home assistant has been purposely disabled.
