### ISSUE TITLE
Hub Discovery Not Working

### ISSUE THREAD

**Issue by alexyao2015** [hass-emulated-hue/core#52]
HueManic and Sleep as Android from the same developer will not find the bridge automatically. It seems likely that the issue is related to incorrect data in the SSDP response as the emulator responds but the app does not find it.

Manual pairing now works with the #51

**Comment by marcelveldt** [comment]
Or that app uses N-UPNP (discovery.meethue.com)...

**Comment by alexyao2015** [comment]
I don't think thats the case since I saw the search request and believe it was automatically discovered with diyhue.

**Comment by marcelveldt** [comment]
Maybe ping the developer of those apps what he's looking for in the SSDP request ?

**Comment by alexyao2015** [comment]
Seems like automatic discovery is not working with diyhue either. Will need to look further into the issue. ATM I see M-SEARCH requests with a response. Presumably, something is wrong there as there are no requests to description.xml at all.

**Comment by alexyao2015** [comment]
Harmony hub is also not able to discover the bridge. This works with the native emulated_hue component within HA, so we may need to look there to see what is missing. Very similar symptoms as HueManic with SSDP responses being sent numerous times but no description.xml.

**Comment by JonOve** [comment]
Hello Alex,

Actually just tried it an hour ago and it worked like a charm. The Harmony hub found the emulated V2 bridge rather quick. Had to enable the connection link in notifications in HA and done. Lights are found. Switches not however. Therefor I also moved back to the V1 integration for Harmony.

Verstuurd vanaf mijn iPad

**Comment by alexyao2015** [comment]
That's very surprising. I wasn't able to discover it with Harmony until I implemented a patch that fixed discovery here. Are you able to discover it with HueManic, the app? What version are you running?

As a workaround for switches, you can use a template light to control switches.

**Comment by JonOve** [comment]
Hello Alex,

I am using the latest version of HA 20202.12.2 on a RPI4, 8gb.
Harmony hub integration is not active in HA. Harmony found the hass emulated Hue addon straight away and also the original Hue app found it correctly. Not all features worked in the original app, I.e. lamp updates. What might be a topic is that I used to have the original Hue hub connected a few months ago to as well the Harmony hub as the Hue app.

I do not use Hue Manic. If important for you I will give it a try. Let me know!

Verstuurd vanaf mijn iPad

**Comment by alexyao2015** [comment]
Hmm interesting. I've tried it on my dev instance and it definitely wasn't being recognized. Perhaps harmony stored the ip that it previously discovered and used that. Couple questions, if you change the ip address, does it still discover it? Are you using the new hassio repository? https://github.com/hass-emulated-hue/hassio-repo
Are you running the stable or dev add-on? 

If you would be able to test the app HueManic, that would be great! Ultimately, we would want to bring this to full compatibility with any and all Hue apps/clients.

**Comment by JonOve** [comment]
The IP address of my RPI is different from the my former Hue bridge, so yes, it connects to a different IP address. And the repo you mention is the one I use. I run the stable version of the addon. HueManic is not available in the iOS App Store unfortunately. So I am not able to support you with that.

Verstuurd vanaf mijn iPad

**Comment by alexyao2015** [comment]
How did you pair the bridge? Did you remove and readd it or did you tap "re-pair bridge"? Would you able be able to test out the dev addon as well? It seems to be very hit or miss for me although I have only done re-pair bridge since I didn't want to setup all my activities again. Personally, I've seen it pair once and never saw the pairing request come through again. Really unsure what is going on here.

**Comment by JonOve** [comment]
Hello,

I did a "re-pair" on the Harmony app and the "stable" V2 bridge was found
immediately. Just a few minutes ago I installed the "dev" V2 bridge and
also this one is found via re-pair immediately in the Harmony app. Nothing
functions however, so I now moved back to the stable version.

Btw I used the template light as you mentioned in an earlier mail for 2
switches. They are now found in the Harmony app, but connected to the Home
Control buttons they do not function, while they do function well in the V1
integration of HA.
In the Harmony app you have to key in whether you want the switches to be
seen as a switch or as a light. I tried both options, but neither of the 2
options make the switches react to the Home Control buttons.

Op do 7 jan. 2021 om 06:54 schreef Alex <notifications@github.com>:

**Comment by alexyao2015** [comment]
What do you mean by nothing functions on the dev version? That version should be pretty stable too. Did you uninstall the stable version first? 

I'll trust that it's working for Harmony then and it might be an issue with my Harmony or something.

The home control buttons should be fine since they act as lights instead. Not sure what you mean by them not working.

**Comment by JonOve** [comment]
I stopped the stable version and started the dev version. Sounds okay to me. Not?
While running the dev version, the virtual bridge was found by the Harmony hub, but the Harmony control buttons did not function. I did a repair in the Harmony app on the dev bridge upfront.

Then I stopped the dev version and started the stable version. I did a re-pair on the Harmony hub. The Harmony control buttons function for the actual RGB lights, but not completely for the switches. No matter whether I configure them in the Harmony app as a switch or a light. The Harmony control buttons turn the switch off, but not on. 

Now I have the virtual bridge paired also to my Philips TV. Pairing went well. The lamps responded as being paired, but that is it. They do not react to a change of colour with ambilight.

Let me know your questions or required tests.

Verstuurd vanaf mijn iPad

**Comment by alexyao2015** [comment]
When you create a template light, you must make sure to specify both a turn on and turn off action. That is likely why it only works one way. 

Would you be able to again install the dev version and test one by one until you find where the dev version starts working again like the current stable? Try these values in the configuration option "tag_commit_or_branch". Then restart the plugin. Please let me know the results for each of them and if they work.

1. dfb67525e3b9b7a775c6e89560b04ab3d8fc0c2c
2. eb8ba05425dae45438ec53b3df997637b65de7f1
3. d3659844578fb2dc5c3a434a8652caae4f0e422b

**Comment by JonOve** [comment]
Okay, thanks. I used the standard template with only the entity mentioned.
I will make the changes and deal with requested tests tomorrow. Will let you know asap.
Is it correct the ambilight function on the stable version is not working?

Verstuurd vanaf mijn iPad

**Comment by JonOve** [comment]
Btw. I also connected the stable version bridge to the original Hue app. In there lights work properly, including scenes, colour adjustment and brightness. Switches on / off also function well.

Verstuurd vanaf mijn iPad

**Comment by alexyao2015** [comment]
I'm not sure if Ambilight is working or not. I don't use that. The stable version working is as expected. If you happened to have an original Hue bridge, you would be able to help with further testing. If not, just try testing those things from earlier and let me know.

**Comment by JonOve** [comment]
All three values function equal to the stable version.
Only with the 1st value it is possible to re-pair the virtual bridge to the
Harmony hub. The other 2 values are not found while re-pairing.

Btw; I have a spare Harmony hub, which was not paired to the original Hue
hub before. While trying to pair this hub to the virtual V2 bridge all
versions fail. Stable as well as the dev versions.

Op do 7 jan. 2021 om 19:34 schreef Alex <notifications@github.com>:

**Comment by alexyao2015** [comment]
You mentioned you have a spare Harmony hub that hasn't been able to pair at all while the previously paired one does work? Try this commit using the one that does not pair at all. e1cd37846cf6359f6769e40b171451a377cc5b47

**Comment by JonOve** [comment]
Commit  e1cd378
<https://github.com/hass-emulated-hue/core/commit/e1cd37846cf6359f6769e40b171451a377cc5b47>
works.
Connection is made fine.

On your former remark, I changed the switch to a light with the platform
"template".
Although in HA it is found as a light, in the Harmony app it is still seen
as a switch however.

Function "all lights" functions well.
Individually only the Hue lights respond.

Function "all switches" functions well.
Individually no switch responds.


Op vr 8 jan. 2021 om 19:57 schreef Alex <notifications@github.com>:

**Comment by alexyao2015** [comment]
Great! Seems that there was something that we needed to change there. Can you try this and see if it still pairs? 

fix/api-inconsistencies

**Comment by JonOve** [comment]
Removed the former virtual bridge from the Harmony hub and re-paired using "fix/api-inconsistencies" And Yes, it pairs. Individual lights now work also, as well as zigbee2mqtt light groups. Individual switches still fail.

**Comment by alexyao2015** [comment]
Great! What do you mean by individual switches fail btw? 
Also do you happen to have an original hue bridge around.

**Comment by JonOve** [comment]
Using the platform template in HA I created some lights, while they actually are switches. In HA and the original Hue app (using your virtual bridge) they are found as a light and function well. In The Harmony app they still are found as a switch. They only function on/off in Harmony using the group "all switches". Individually they do not respond. And yes, I should have the original Hue hub somewhere lying around still.

**Comment by alexyao2015** [comment]
Hmm that is very odd. Since this is not a discovery issue, could you please create a new issue so this problem doesn't get lost in the comments here?

**Comment by JonOve** [comment]
Seems to be fixed using "master"

**Comment by alexyao2015** [comment]
Hmm that seems very strange. You're saying that it works in "master", but does not work in "fix/api-inconsistencies"? That is rather peculiar given that "fix/api-inconsistencies" should contain all the fixes in master and then some. Can you try 636e83c5fed4e370240f93c55daa13741c1546fc?

**Comment by JonOve** [comment]
In “636e83c” the individual switch does not work either. Checked “ fix/api-inconsistencies” again and the switch did not work. Moved back to “master” and the individual switch works perfect.

Verstuurd vanaf mijn iPad

**Comment by alexyao2015** [comment]
Well in that case, something is wrong with how you're testing it because "fix/api-inconsistencies" is based off that commit and master also has that commit. Since then, there have been no real changes to master that affected the API. How exactly are you testing "master"? You're using the dev addon right?

**Comment by JonOve** [comment]
That might be;
I delete the virtual bridge from the Harmony hub, then synchronise the Harmony hub with the Harmony server.
Then change the branche nr in the HA addon, dev version and restart the addon. Then add the virtual bridge back again to the Harmony hub. And start the testing.

**Comment by alexyao2015** [comment]
Wipe entire config folder between tests as well. Backup your current config folder if you would like before wiping it.

**Comment by JonOve** [comment]
I guess you mean this file “ emulated_hue_ids.json”? Or do you really mean the complete folder in HA config “ hass-emulated-hue”?
Will I then need to reinstall the addon? Or will a restart create the folder again?


Verstuurd vanaf mijn iPad

**Comment by alexyao2015** [comment]
Stop the addon, delete the entire folder, then start the addon. No need to reinstall.

**Comment by JonOve** [comment]
Followed your instructions; do not shoot the messenger, but the result is the same.
In all 3 commits zigbee light groups work and individual lights work in Harmony. Only in “master” the switches work individually.

Verstuurd vanaf mijn iPad

**Comment by alexyao2015** [comment]
Ok then, what happens if you try 8036c1517c2270e752157afa81086a82d2de8b5f?

**Comment by JonOve** [comment]
"8036c15" works equal to "master". Zigbee groups and individual lights work well. Individual switches work well also!

**Comment by alexyao2015** [comment]
Interesting. So if you try this, does it stop working? d4dede2f5662a12c36c9ea2d7b875a6eadc224ed

**Comment by JonOve** [comment]
Using "d4dede2" zigbee groups work, individual lights work. Indeed switches fail.

**Comment by alexyao2015** [comment]
Ok seems like a side effect of my brightness fix was that it also somehow fixes switches? Anyways, if you try master now, it still should work. Some major changes were merged today.

**Comment by JonOve** [comment]
Using “master” indeed all works well.

Verstuurd vanaf mijn iPad

**Comment by JonOve** [comment]
We can close this topic

**Comment by alexyao2015** [comment]
Well no because the real original issue of HueManic and Sleep as Android still do not function.

**Comment by JonOve** [comment]
After this mornings update to 0.2.0 Harmony and the Hue app lost connection and are not able to re-pair. Deleted all the files from as well Harmony as from HA config. Re-installed the add-on. But both "stable" as "dev" are not found.

**Comment by JonOve** [comment]
To add; the virtual bridge enables the connection link in HA, while the Harmony app and the Hue app are not able to find the bridge and are not requesting to push the link button on the Hue bridge.

**Comment by JonOve** [comment]
Okay, after a restart of HA also the "enable link" is no longer activated.

**Comment by alexyao2015** [comment]
I can confirm that it still works with the Hue app, but I haven't tested Harmony yet with it. The changes released shouldn't have had any affect on discovery or pairing. Try reinstalling the Hue app and the Harmony app, then try it again. 

As this thread is becoming quite long, would you be able to make further comments in a discussion instead?

**Comment by tmarquespt** [comment]
I'm migrating from old hue emulation on HA to this addon. The hue app on my phone found the emulation but my Harmony can«t find it. I tried the dev version and I can see the HA .5.206 talking to the harmony .5.9

(...)
2021-02-03 22:55:12,040 DEBUG emulated_hue.discovery -- Serving SSDP discovery info to ('10.11.5.206', 53738)
2021-02-03 22:55:12,041 DEBUG emulated_hue.discovery -- Serving SSDP discovery info to ('10.11.5.206', 53738)
(....)

It gives me like 20 lines or so with the harmony ip and then it stops. On the harmony app says 'No Philips Hue Bridge was detected'. There's no notification in HA to pair like when I was pairing the hue app

I removed the old hue emulation, restarted HA, restarted harmony hub made multiple sync request but no success.

Any hints on how to proceed?

thks

**Comment by alexyao2015** [comment]
Further testings shows that hue discovery works fine on Android 8 using the same version of the app but fails on Android 11. Seems to be an issue with the app itself rather than the emulator.

@tmarquespt 
Can you please create your own discussion so that we can look at this issue further? If necessary, we can then create a new issue.
