### ISSUE TITLE
Please don't let this project die...

### ISSUE THREAD

**Issue by cibrenvenuti** [hass-emulated-hue/core#524]
### Description

This project was one of the best, one that had been anticipated for a long time, one of the most useful Home Assistant addons. Until it worked... It's a real shame to see it die. There's still a lot of interest around it; it would be great if the one who started it or someone else continued the development. Please don't make me go back to using the cursed Philips bridge just to have the entertainment of Hue Essentials! 😞

### Use Case

As above

**Comment by cibrenvenuti** [comment]
I understood, I think: this project is dead. 😞

**Comment by alexyao2015** [comment]
The project isn't dead, but it's been on my back burner for quite sometime. If you're wondering when you'll see the v2 update, it'll probably be sometime. I haven't been able to put a whole lot of time/interest to put into side projects unfortunately.

**Comment by egore** [comment]
I've tried looking into the v2 API and what would be needed to implement this. diyHue implements the v2 API (see https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/HueEmulator3.py#L76) and it didn't look to complicated. Unfortunately I was wrong and my limited python skills prevented me from getting far enough.

I understood that you need to call /auth/v1 once to obtain your authorized username, which needs to be passed to any subsequent call as header hue-application-key. I've stubbed out some methods but currently failed at testing it locally.

Is there a documentation on how to run it locally for testing purposes?

I've also came up with an openapi generator, that will parse the non-public documentation of the developer portal and produce a standard openapi.yaml from it: https://gitlab.com/egore/hue-openapi-gen

**Comment by egore** [comment]
I've uploaded my (incomplete and untested) implementation of the GET /clip/v2/resource/light API to https://github.com/egore/hass-emulated-hue

**Comment by alexyao2015** [comment]
In #490 , it seems like someone did some work on the v2 API as well. I haven't taken a look at it but it might be worth looking into if you are working on this.

**Comment by cdjm** [comment]
This project could act as a plug & play addon to home assistant just as the included one did before.
There are a lot of guys around me who are just waiting for an easy way to make their lights avilable to Alexa without having to configure every light twice.

I think there is also a lot achieveable besides the upgrade to the v2 API.
At the moment there are still some quirks with the light configuration as hass_emulated_hue replies with a quite general result for bulb types. Reviewing this could maybe make the support for sensors possible.

Also fixing the model-id (see my PR) makes Hue Essential a lot more happy than listing a bunch of invalid bulbs.

I would happily try to help but as a python noob I am still trying to dig into your code :-(
At least I have all the necessary devices (Bulbs [Hue, Ikea, innr, Lightify], Sensors, Thermostats) and bridges (Hue Bridge, Conbee, Zigbee2MQTT) here to do some testing and send you some API replies for hardware if necessary.

In any case I would gladly help.

**Comment by BlackTurtle123** [comment]
Did someone end up working on this?

**Comment by egore** [comment]
The best solution from my perspective still is #490, though I did not yet have the time to look into it. Based on my (limited) knowledge the implementation seems usable enough.

**Comment by egore** [comment]
For the time PR #490 is not merged, you can use the following repository to install this on your installation: https://github.com/cvele/hassio-repo. Please note that this is **not** the official addon.

This still is not enough to get the hue app running, as it still insists on updating the bridge. Likely in [cvele's fork](https://github.com/cvele/hass-emulated-hue-core/blob/master/emulated_hue/apiv2.py#L496C43-L496C53) the version number needs to be bumped to "1.62.1962154010" (for which I have created a PR at his repo https://github.com/cvele/hass-emulated-hue-core/pull/2)
