### ISSUE TITLE
Idea: Manual light importing

### ISSUE THREAD

**Issue by alexyao2015** [hass-emulated-hue/core#54]
Disable automatic importing of lights and only add new lights if lights are scanned for. To restore deleted lights, enter a magic "serial" when light scanning that will all lights back.

This would help with users that add new lights but may not want them all to appear in the app, removing the need for any sort of manual configuration.

May replace #46

**Comment by marcelveldt** [comment]
Sorry but no for reasons I previously explained. The HASS state should be reflected as this is a HASS --> HUE emulator. It means that HASS is in charge. Users wanting it otherwise have an alternative which is diyhue.
