### ISSUE TITLE
Persistent config

### ISSUE THREAD

**Issue by Mr-Groch** [hass-emulated-hue/core#58]
**Is your feature request related to a problem? Please describe.**

Yes - its frustrating when I lost my config over and over :)

**Describe the feature that you would like to be added**

Please add possibility to export/import config or move caonfig file to shared folder outside docker container so it will survive addon reinstall/switching branches

**Describe alternatives you've considered**

I was able to backup and restore my config few times, but not not always I remember to do it... It is also not easy for casual user.

**Describe your use case for this feature**

I think that better will be to use shared folder for config and cert files

**Additional context**

...

**Comment by alexyao2015** [comment]
This actually has been done! It's now stored in the config folder with all your other configuration files
