### ISSUE TITLE
HA event on HUE entertaiment start

### ISSUE THREAD

**Issue by zewelor** [hass-emulated-hue/core#64]
**Is your feature request related to a problem? Please describe.**

**Describe the feature that you would like to be added**

I think it would be nice to send some HA event ( or something other ? ) when entertaiment starts. It could be used to prepare lights for increased traffic ( for example in yeelight, turn on music mode, no limit for changes per minute then ). Maybe also react on it somehow ( turning off other lights etc ? ).

**Describe alternatives you've considered**

Doing automation that would turn on docker with emulated hue, and start music_mode for yeelights I would like to use with hue

**Describe your use case for this feature**

**Additional context**

Thanks for great addon !

**Comment by alexyao2015** [comment]
I believe that music_mode for yeelights is a config option that is either always on or always off for HA. Emulated Hue should always be on otherwise you wouldn't be able to start entertainment mode in the first place. Perhaps the only real use case is using it as an automation to turn off other lights, but this would be a pretty low priority enhancement if that is the case since the use cases are extremely limited.

**Comment by zewelor** [comment]
Thanks for answer. I've made PR with service to enable / disable yeelight music mode on demand ( https://github.com/home-assistant/core/pull/44533 ). Yes I image emulated hue to be on all of the time. When amilight+hue is turned off on tv. It doesn't do anything, when turned on ( on tv ). It starts lights control ( entartaiment mode start in emulated hue, as I saw in logs ). In this case it would be good to do some setup on demand ( at least enable music mode in yeelight case ).

**Comment by alexyao2015** [comment]
I see then. Will look into this eventually, but its likely on the bottom of the to-do list. Feel free to make a PR if you do implement it yourself though!

**Comment by marcelveldt** [comment]
Sending a small event is a small addition that we can add but first we'll have to do the refactor of the logic or else we will end up mad with all new features ;-)

**Comment by alexyao2015** [comment]
BTW, Yeelight won't work with entertainment until #80 is resolved.

**Comment by marcelveldt** [comment]
adding an event required a change in the HA library so instead I've added a binary sensor **binary_sensor.emulated_hue_entertainment_active**

will be available in next release

**Comment by zewelor** [comment]
Great thanks !
