### ISSUE TITLE
Invalid/unknown request: <Request PUT /api/c013fbe396b847f9a306/groups/ > --> {'stream': {'active': False}}

### ISSUE THREAD

**Issue by Mr-Groch** [hass-emulated-hue/core#67]
**Describe the bug**

I'm getting warning in logs when I'm disabling Ambilight+Hue on non-Android Philips TV

**Steps to Reproduce**

1. Turn Ambilight+Hue on
2. Turn Ambilight+Hue off
3. Observer Warning in logs

**Expected behavior**

No warning on disabling Ambilight+Hue

**Logs**

`2021-01-10 12:39:21,495 WARNING emulated_hue.api -- Invalid/unknown request: <Request PUT /api/c013fbe396b847f9a306/groups/ > --> {'stream': {'active': False}}`

**Hardware Info:**
 - Architecture (Ex: x86, ARM): ARMv7
 - Addon version (Ex: stable or dev): stable
    - Value of "tag_commit_or_branch" if using dev: 
 - OS (Ex: Windows 10, Ubuntu Buster): HassOS
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): RPI 3

**Additional context**

**Comment by alexyao2015** [comment]
That's peculiar. Do you see those exact same logs every time you turn it off?  Strange that there's no group id there.  What happens if you create another entertainment area then try it again?

**Comment by Mr-Groch** [comment]
Firstly - I'm not using entertainment area, my non-Android Philips TV use standard API for ambilight+hue. This warning sometimes shows, sometimes not.. Today morning this warning was happening every time, but now when I toggle Ambilight+Hue on/off it dosn't appear.. Don't know why sometimes my TV is sending that request...

**Comment by alexyao2015** [comment]
Hmm I would assume this would be similar to #63. Any request that has an unknown or no group id should be considered group 0. Lets group this issue with the group 0 bug there to be fixed.
