### ISSUE TITLE
Properly show state for xy, ct color modes

### ISSUE THREAD

**Issue by alexyao2015** [hass-emulated-hue/core#72]
**Describe the bug**

We currently set the state as a static xy or ct depending on the bulb type instead of setting it to whatever mode the light is currently in. We would first need to figure out a way to get the light mode, ct or xy, from HASS then display that accordingly. A problematic issue is that I do not see any data from HASS that tells me if the device is in ct or xy/rgb mode. 

https://github.com/hass-emulated-hue/core/blob/cd9a5eb6357fd1bfea402592fd3f24817c492bc8/emulated_hue/api.py#L702

**Steps to Reproduce**

**Expected behavior**

Keeping a static xy/color mode confuses apps like Hue Essentials into showing weird info.

**Logs**

**Hardware Info:**
 - Architecture (Ex: x86, ARM): 
 - Addon version (Ex: stable or dev): 
    - Value of "tag_commit_or_branch" if using dev: 
 - OS (Ex: Windows 10, Ubuntu Buster): 
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): 

**Additional context**

**Comment by marcelveldt** [comment]
Correct, that is annoying. Hass will return all possible values, depending on the light implementation.
Best way to do it is just listen for state changed events and store the state.

**Comment by alexyao2015** [comment]
Yes that would be a good alternative as well. Perhaps we also should store the previous xy color set on the light as well to prevent it from showing up as 0,0 if the light changes to ct mode.

**Comment by marcelveldt** [comment]
Yes, that's what I mean. Listen for state_changed events from the HA entity and store color_temp or color values.
if color_temp changes, CT is active and if color changes, color mode is active.

**Comment by marcelveldt** [comment]
HA will always report all color modes/types as it will calculate to/from the different types.
Only thing we NEED to know if it's actually running in color_temp mode or color (RGB/XY/HS) mode

**Comment by TheJulianJES** [comment]
Not sure if this is related, but since https://github.com/home-assistant/core/pull/44566 and https://github.com/home-assistant/core/pull/44829 were merged (2021.1.0), Home Assistant should only have ``color_temp`` or ``xy_color`` as an attribute for the state (depending on what color mode the light is in).

**Comment by marcelveldt** [comment]
ah, I missed that. Thanks!!

**Comment by marcelveldt** [comment]
While I agree with you that all implementations *should* handle it like this, this isn't the case.
For example esphome lights will return all possible values, regardless of what mode the light is actually in.


<img width="288" alt="Schermafbeelding 2021-01-16 om 00 55 31" src="https://user-images.githubusercontent.com/6389780/104789509-8a7b1d80-5795-11eb-94fb-82227941ee18.png">

**Comment by alexyao2015** [comment]
fixed in #196
