### ISSUE TITLE
Add support for HueLabs

### ISSUE THREAD

**Issue by ThauEx** [hass-emulated-hue/core#96]
**Is your feature request related to a problem? Please describe.**

When trying to install anything for HueLabs, an error pops up.    
This appears in the log:
```
WARNING emulated_hue.api -- Invalid/unknown request: <Request POST /api/a7fedd00-4ea5-4ad1-9705-e7e376b38f63/sensors/ > --> {'name': 'Start and stop', 'modelid': 'HUELABSVDIMMER', 'swversion': '1.0', 'type': 'CLIPGenericStatus', 'manufacturername': 'Philips', 'uniqueid': 'fdc3-2a4c-44b9-84cf', 'recycle': True}
```

**Describe the feature that you would like to be added**

Support for HueLabs effects.

**Describe alternatives you've considered**

**Describe your use case for this feature**

**Additional context**

**Comment by alexyao2015** [comment]
This is #50 which hasn't been implemented yet.
