### ISSUE TITLE
Philips hue app don't work. Hue Essencials dont work. My TV philips ambient light get the hub, but can set anycolor to find it bulbs

### ISSUE THREAD

**Issue by DavidFFerreira** [hass-emulated-hue/core#98]
Philips hue app don't work. Hue Essencials dont work. My TV philips ambient light get the hub, but can set anycolor to bulbs. I can set wifi bulbs, but aftert I try to set up a zigbee bulb the tv restarts itself

**Comment by alexyao2015** [comment]
Please fill out the entire template or create a discussion
