### ISSUE TITLE
Zigbee Bulbs crash TV after try to set up

### ISSUE THREAD

**Issue by DavidFFerreira** [hass-emulated-hue/core#99]
**Describe the bug**

I did a fresh install, all good no errors. Por 443 and 80 are avaliable for this.
My TV is a philips ambientlight with SaphiOS
My tv Find the huebidge and sucesseful find all bulbs

1º Bug: After select the bulbs I want (zigbee ones) to setup the location, the TV restarts it self
2º Bug: Some Philips lights application cant see the zigbee bulbs
I have no errors in logs

If you want I can  make a video

**Steps to Reproduce**
Already describe

THIS IS VERY IMPORTANT TO KNOW TO BE ABLE TO FIX THE BUG!
If at all possible, please try to create reproduction steps from
a clean environment (delete all existing config and reinstall from
scratch). Again, please make sure to read all primers to ensure we 
are able to help you.
-->

**Expected behavior**
Zigbee bulbs avaliability and no crash on TV

**Logs**
No errors

**Hardware Info:**
 - Architecture x86,:
 - Addon versiond ev: 
    - Value of "tag_commit_or_branch" if using dev: 
 - OS: Debian Buster: 
 - Hardware: Intel Compute Stick: 

**Additional context**
![image](https://user-images.githubusercontent.com/32928749/106292347-a0341c80-6244-11eb-906b-162a9dba40f9.png)

**Comment by alexyao2015** [comment]
Please reread the entire template as well as all the primers at the top, then properly complete the template. There is not enough information here.

**Comment by DavidFFerreira** [comment]
just say, you dont care, and you dont want fo fixed. ;=)
